### ISSUE TITLE
downstream-prometheus-scrape-relation-joined hook crashes in rev 51

### ISSUE THREAD

**Issue by przemeklal** [canonical/cos-proxy-operator#102]
### Bug Description

I've experienced a crash in cos-proxy rev 51 in `downstream-prometheus-scrape-relation-joined ` hook crash.

### To Reproduce

Deploy cos-proxy rev 51 and relate it to scrape-interval-config.
Relate an additional nrpe application to cos-proxy.

`juju show-status-log cos-proxy-monitors/4`
```
23 Nov 2023 13:28:15Z  juju-unit  executing    running monitors-relation-changed hook for nrpe-lxd/1                                                                                                                                           
23 Nov 2023 13:28:17Z  juju-unit  idle                                                                                 
23 Nov 2023 13:29:15Z  juju-unit  executing    running downstream-prometheus-scrape-relation-created hook                                                                                                                                      
23 Nov 2023 13:29:16Z  juju-unit  executing    running downstream-prometheus-scrape-relation-joined hook for cos-scrape-interval-config-monitors/0                                                                                             
23 Nov 2023 13:42:21Z  juju-unit  error        hook failed: "downstream-prometheus-scrape-relation-joined"                                                                                                                                     
23 Nov 2023 13:42:26Z  juju-unit  executing    running downstream-prometheus-scrape-relation-joined hook for cos-scrape-interval-config-monitors/0                                                                                             
23 Nov 2023 13:55:41Z  juju-unit  error        hook failed: "downstream-prometheus-scrape-relation-joined"                                                                                                                                     
23 Nov 2023 13:55:51Z  juju-unit  executing    running downstream-prometheus-scrape-relation-joined hook for cos-scrape-interval-config-monitors/0                                                                                             
23 Nov 2023 14:09:18Z  juju-unit  error        hook failed: "downstream-prometheus-scrape-relation-joined"                                                                                                                                     
23 Nov 2023 14:09:38Z  juju-unit  executing    running downstream-prometheus-scrape-relation-joined hook for cos-scrape-interval-config-monitors/0                                                                                             
23 Nov 2023 14:23:19Z  juju-unit  error        hook failed: "downstream-prometheus-scrape-relation-joined"                                                                                                                                     
23 Nov 2023 14:24:00Z  juju-unit  executing    running downstream-prometheus-scrape-relation-joined hook for cos-scrape-interval-config-monitors/0                                                                                             
23 Nov 2023 14:37:25Z  juju-unit  error        hook failed: "downstream-prometheus-scrape-relation-joined"                                                                                                                                     
```

### Environment

cos-proxy rev 51

### Relevant log output

```shell
unit-cos-proxy-monitors-4: 14:46:39 ERROR unit.cos-proxy-monitors/4.juju-log downstream-prometheus-scrape:566: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-cos-proxy-monitors-4/charm/./src/charm.py", line 517, in <module>
    main(COSProxyCharm)
  File "/var/lib/juju/agents/unit-cos-proxy-monitors-4/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-cos-proxy-monitors-4/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-cos-proxy-monitors-4/charm/venv/ops/framework.py", line 340, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-cos-proxy-monitors-4/charm/venv/ops/framework.py", line 842, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-cos-proxy-monitors-4/charm/venv/ops/framework.py", line 931, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-cos-proxy-monitors-4/charm/./src/charm.py", line 442, in _downstream_prometheus_scrape_relation_joined
    self._on_nrpe_targets_changed(None)
  File "/var/lib/juju/agents/unit-cos-proxy-monitors-4/charm/./src/charm.py", line 475, in _on_nrpe_targets_changed
    for alert in event.current_alerts:
AttributeError: 'NoneType' object has no attribute 'current_alerts'
```

**Comment by przemeklal** [comment]
No alert rules or scrape jobs are being set up in prometheus as a result of this bug, it's quite critical.

**Comment by jeffreychang911** [comment]
Hi, SolQA saw this happened multiple times in last 2 days after recent COS update.
[run1](https://solutions.qa.canonical.com/testruns/fc692144-099c-41a0-bca5-0552c4ae81f3), [run2](https://solutions.qa.canonical.com/testruns/2e37c3d4-9426-47db-bccb-c37039c59a40), 

logs are almost identical
2023-12-13 07:07:28 DEBUG unit.cos-proxy/0.juju-log server.go:325 downstream-prometheus-scrape:34: ops 2.8.0+8.g26c6e95 up and running.
2023-12-13 07:07:28 DEBUG unit.cos-proxy/0.juju-log server.go:325 downstream-prometheus-scrape:34: Emitting Juju event downstream_prometheus_scrape_relation_joined.
2023-12-13 07:07:29 ERROR unit.cos-proxy/0.juju-log server.go:325 downstream-prometheus-scrape:34: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 517, in <module>
    main(COSProxyCharm)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/framework.py", line 340, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/framework.py", line 842, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/framework.py", line 931, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 442, in _downstream_prometheus_scrape_relation_joined
    self._on_nrpe_targets_changed(None)
  File "./src/charm.py", line 475, in _on_nrpe_targets_changed
    for alert in event.current_alerts:
AttributeError: 'NoneType' object has no attribute 'current_alerts'
