### ISSUE TITLE
Regression: revision 61 crashes when relating over :monitors to nrpe running on physical machines

### ISSUE THREAD

**Issue by przemeklal** [canonical/cos-proxy-operator#119]
### Bug Description

This validation code https://github.com/canonical/cos-proxy-operator/blame/main/lib/charms/nrpe_exporter/v0/nrpe_exporter.py#L456 introduced in https://github.com/canonical/cos-proxy-operator/commit/7fce85da8e246f9307b3c3db32c52f9f72b1afc5 results in cos-proxy entering `error` state with the following trace:

```
unit-cos-proxy-monitors-1: 09:37:05 ERROR unit.cos-proxy-monitors/1.juju-log monitors:556: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-cos-proxy-monitors-1/charm/./src/charm.py", line 498, in <module>
    main(COSProxyCharm)
  File "/var/lib/juju/agents/unit-cos-proxy-monitors-1/charm/venv/ops/main.py", line 456, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-cos-proxy-monitors-1/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-cos-proxy-monitors-1/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-cos-proxy-monitors-1/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-cos-proxy-monitors-1/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-cos-proxy-monitors-1/charm/lib/charms/nrpe_exporter/v0/nrpe_exporter.py", line 300, in _on_nrpe_relation_changed
    endpoints, alerts = self._generate_data(relation)
  File "/var/lib/juju/agents/unit-cos-proxy-monitors-1/charm/lib/charms/nrpe_exporter/v0/nrpe_exporter.py", line 444, in _generate_data
    alerts.append(self._generate_alert(relation, cmd, id, unit))
  File "/var/lib/juju/agents/unit-cos-proxy-monitors-1/charm/lib/charms/nrpe_exporter/v0/nrpe_exporter.py", line 460, in _generate_alert
    raise ValueError(f"Invalid unit identifier '{id}': expected a string like 'unit-0'")
ValueError: Invalid unit identifier 'redacted-redacted001': expected a string like 'unit-0'
```

Where `redacted-redacted001` is the value of `target-id` provided by the nrpe charm (rev 75, quite old but all revisions do the same, including very fresh rev 106 on jammy clouds).

Can this validation be please removed or adjusted so that it supports arbitrary hostnames?

### To Reproduce

Relate cos-proxy rev 61 to nrpe charm that runs on a physical server or a VM with a hostname that doesn't match the pattern.

### Environment

Details above.

### Relevant log output

```shell
Details above.
```

**Comment by sed-i** [comment]
Sorry about that, was not aware of the arbitrary hostname usecase.
Fix coming up shortly.
