### ISSUE TITLE
Scaling up the cos-proxy ends up with non-leaders erroring

### ISSUE THREAD

**Issue by simskij** [canonical/cos-proxy-operator#40]
### Bug Description

COS Proxy tries to write to application data even from units that are not currently the leader. This makes them crash.

### To Reproduce

1. Deploy COS Proxy
2. Scale it to two
3. 💣 

### Environment

N/A

### Relevant log output

```shell
unit-cos-proxy-5: 16:16:53 ERROR unit.cos-proxy/5.juju-log downstream-grafana-dashboard:614: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 431, in <module>
    main(COSProxyCharm)
  File "/var/lib/juju/agents/unit-cos-proxy-5/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-cos-proxy-5/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-cos-proxy-5/charm/venv/ops/framework.py", line 354, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-cos-proxy-5/charm/venv/ops/framework.py", line 830, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-cos-proxy-5/charm/venv/ops/framework.py", line 919, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-cos-proxy-5/charm/lib/charms/grafana_k8s/v0/grafana_dashboard.py", line 1688, in _update_remote_grafana
    grafana_relation.data[self._charm.app]["dashboards"] = json.dumps(stored_data)
  File "/var/lib/juju/agents/unit-cos-proxy-5/charm/venv/ops/model.py", line 1473, in __setitem__
    self._validate_write(key, value)
  File "/var/lib/juju/agents/unit-cos-proxy-5/charm/venv/ops/model.py", line 1459, in _validate_write
    raise RelationDataAccessError(
ops.model.RelationDataAccessError: cos-proxy/5 is not leader and cannot write application data.
```

**Comment by rbarry82** [comment]
Will be closed in #44
