### ISSUE TITLE
Can't import ceph-dashboards via cos-proxy.

### ISSUE THREAD

**Issue by peppepetra** [canonical/cos-proxy-operator#48]
### Bug Description

When importing ceph-dashboards via cos-proxy `dashboards-relation-changed` hook goes into error state.

### To Reproduce

1. `juju add-relation ceph-dashboard:grafana-dashboard cos-proxy:dashboards`

### Environment

cos-proxy rev. 22 channel edge 

### Relevant log output

```shell
unit-cos-proxy-0: 09:26:52 INFO juju.worker.uniter awaiting error resolution for "relation-changed" hook
unit-cos-proxy-0: 09:27:12 INFO juju.worker.uniter awaiting error resolution for "relation-changed" hook
unit-cos-proxy-0: 09:27:13 DEBUG unit.cos-proxy/0.juju-log dashboards:479: Operator Framework 2.1.1+2.geb8e25a up and running.
unit-cos-proxy-0: 09:27:13 DEBUG unit.cos-proxy/0.juju-log dashboards:479: Emitting Juju event dashboards_relation_changed.
unit-cos-proxy-0: 09:27:13 ERROR unit.cos-proxy/0.juju-log dashboards:479: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 464, in <module>
    main(COSProxyCharm)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/framework.py", line 354, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/framework.py", line 830, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/framework.py", line 919, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/lib/charms/grafana_k8s/v0/grafana_dashboard.py", line 1659, in update_dashboards
    self._upset_dashboards_on_event(event)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/lib/charms/grafana_k8s/v0/grafana_dashboard.py", line 1663, in _upset_dashboards_on_event
    dashboards = self._handle_reactive_dashboards(event)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/lib/charms/grafana_k8s/v0/grafana_dashboard.py", line 1809, in _handle_reactive_dashboards
    dash = json.dumps(dash)
  File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Circular reference detected
unit-cos-proxy-0: 09:27:13 ERROR juju.worker.uniter.operation hook "dashboards-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-cos-proxy-0: 09:27:13 INFO juju.worker.uniter awaiting error resolution for "relation-changed" hook
```

**Comment by rbarry82** [comment]
I can't reproduce this @peppepetra -- do you know/remember which version of `ceph-dashboard` you were using?

**Comment by rbarry82** [comment]
I mean, I'm not in a situation to actually deploy the charm (way too many moving parts to get it to actually send dashboards -- 3 osds, 3 mons, mgr, maybe more), but this also isn't reproducible from the `stable/quincy.2` branch that it looks like that was built from. When there's a new build of cos-proxy up tomorrow, I guess we can test and see
