### ISSUE TITLE
COS-Proxy in an LXD in the error state (`hook failed: "downstream-logging-relation-changed"`) due to DNS errors after trying to resolve Kubernetes service FQDN

### ISSUE THREAD

**Issue by przemeklal** [canonical/cos-proxy-operator#87]
### Bug Description

I encountered a cos-proxy instance in the error state, failing on DNS resolution. I managed to trace DNS queries and it appears that an LXD in my Openstack model tries to resolve Loki's Kubernetes service address:
```
13:18:45.046592 00:16:3e:xx:xx:xx > xx:xx:xx:xx:xx:xx, ethertype IPv4 (0x0800), length 145: (tos 0x0, ttl 64, id 41035, offset 0, flags [none], proto UDP (17), length 131)
    x.x.x.x.54973 > y.y.y.y.53: 28560+ [1au] AAAA? loki-0.loki-endpoints.cos.svc.cluster.redacted.redacted.redacted. (103)                                                                                           
```
Since Openstack LXDs don't have access to Kubernetes DNS, it fails and the charm is stuck in the error state.

### To Reproduce

Relate cos-proxy in a MAAS Juju model running in an LXD to loki running on microk8s.

### Environment

cos-proxy rev 46 (latest/edge) in a MAAS model (running in a jammy LXD)
loki ch:loki-k8s rev 91 (stable) on microk8s

Relation:
```
cos-loki:logging                                                     cos-proxy:downstream-logging                         loki_push_api                   regular      
```

### Relevant log output

```shell
# juju debug-log -i cos-proxy/0

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/./src/charm.py", line 495, in <module>
    main(COSProxyCharm)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/framework.py", line 344, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/framework.py", line 841, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/framework.py", line 930, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/lib/charms/vector/v0/vector.py", line 227, in _on_log_relation_changed
    self.on.config_changed.emit(config=self.config)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/framework.py", line 344, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/framework.py", line 841, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/framework.py", line 930, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/./src/charm.py", line 376, in _write_vector_config
    r = request.urlopen(dest)
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1377, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

# juju status cos-proxy

Unit                           Workload  Agent  Machine  Public address  Ports     Message
cos-proxy/0*                   error     idle   3/lxd/6  y.z.z.z                   hook failed: "downstream-logging-relation-changed"
...
```

**Comment by lucabello** [comment]
Was that **loki** charm related to traefik? Because it seems to be reporting its cluster local address, which shouldn't be the case if there's an `ingress` relation in place.

**Comment by sed-i** [comment]
Seems like we need to add `urllib.error.URLError` to the exception list in addition to HTTPError:
https://github.com/canonical/cos-proxy-operator/blob/ae01db528bbd23d9f40a2364e6dd69b0b60457b7/src/charm.py#L393-L401

**Comment by lucabello** [comment]
This is not relevant anymore; we have no `urlopen` calls in `charm.py`; the charm writes YAML directly
