### ISSUE TITLE
Data is missing from `nrpe_lookup.csv`

### ISSUE THREAD

**Issue by sed-i** [canonical/cos-proxy-operator#88]
### Bug Description

In production deployments of ~100 units, information of about 15 units is missing from the charm-generated `/etc/vector/nrpe_lookup.csv`. Metrics and alerts for the missing units are also (as a result) missing from prometheus.

https://github.com/canonical/cos-proxy-operator/blob/9bb0f2f1fbd48e6b9fcc8c6e3956ace6f205bd1c/src/charm.py#L304-L305

https://github.com/canonical/cos-proxy-operator/blob/9bb0f2f1fbd48e6b9fcc8c6e3956ace6f205bd1c/lib/charms/nrpe_exporter/v0/nrpe_exporter.py#L287-L291

### To Reproduce

After discussing with @przemeklal, a potential reproducer may look like this:

```yaml
bundle: kubernetes
saas:
  remote-3df866476d10436281a222fc8d2fb7b0: {}
applications:
  prom:
    charm: prometheus-k8s
    channel: edge
    revision: 154
    resources:
      prometheus-image: 131
    scale: 1
    constraints: arch=amd64
    storage:
      database: kubernetes,1,1024M
    trust: true
relations:
- - prom:metrics-endpoint
  - remote-3df866476d10436281a222fc8d2fb7b0:downstream-prometheus-scrape
--- # overlay.yaml
applications:
  prom:
    offers:
      prom:
        endpoints:
        - metrics-endpoint
        acl:
          admin: admin
```

```yaml
series: jammy
saas:
  prom:
    url: k8s2:admin/nrpetest.prom
applications:
  cos-proxy:
    charm: cos-proxy
    channel: edge
    revision: 46
    num_units: 1
    to:
    - "0"
    constraints: arch=amd64
  nrpe:
    charm: nrpe
    channel: edge
    revision: 114
  ubuntu:
    charm: ubuntu
    channel: edge
    revision: 24
    num_units: 3
    to:
    - "1"
    - "2"
    - "3"
    constraints: arch=amd64
    storage:
      block: loop,100M
      files: rootfs,100M
machines:
  "0":
    constraints: arch=amd64
  "1":
    constraints: arch=amd64
  "2":
    constraints: arch=amd64
  "3":
    constraints: arch=amd64
relations:
- - ubuntu:juju-info
  - nrpe:general-info
- - nrpe:monitors
  - cos-proxy:monitors
- - cos-proxy:downstream-prometheus-scrape
  - prom:metrics-endpoint
```

### Environment

Jammy machines/series/bases.
cos-proxy latest (rev 46).

### Relevant log output

```shell
2023-09-20 09:23:37 ERROR unit.cos-proxy/0.juju-log server.go:316 monitors:580: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/model.py", line 2723, in _run
    result = subprocess.run(args, **kwargs)  # type: ignore
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-cos-proxy-0/relation-set', '-r', '581', '--app', '--file', '-')' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/./src/charm.py", line 495, in <module>
    main(COSProxyCharm)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/framework.py", line 344, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/framework.py", line 841, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/framework.py", line 930, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/lib/charms/nrpe_exporter/v0/nrpe_exporter.py", line 310, in _on_nrpe_relation_changed
    self.on.nrpe_targets_changed.emit(  # pyright: ignore
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/framework.py", line 344, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/framework.py", line 841, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/framework.py", line 930, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/./src/charm.py", line 448, in _on_nrpe_targets_changed
    self.metrics_aggregator.set_target_job_data(
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/lib/charms/prometheus_k8s/v0/prometheus_scrape.py", line 2108, in set_target_job_data
    relation.data[self._charm.app]["scrape_jobs"] = json.dumps(jobs)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/model.py", line 1494, in __setitem__
    self._commit(key, value)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/model.py", line 1498, in _commit
    self._backend.update_relation_data(self.relation.id, self._entity, key, value)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/model.py", line 3059, in update_relation_data
    self.relation_set(relation_id, key, value, isinstance(_entity, Application))
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/model.py", line 2828, in relation_set
    self._run(*args, input_stream=content)
  File "/var/lib/juju/agents/unit-cos-proxy-0/charm/venv/ops/model.py", line 2725, in _run
    raise ModelError(e.stderr)
ops.model.ModelError: ERROR cannot write relation settings

2023-09-20 09:23:37 ERROR juju.worker.uniter.operation runhook.go:153 hook "monitors-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
```

**Comment by sed-i** [comment]
@przemeklal is this ☝️ an accurate representation?

**Comment by sed-i** [comment]
One possibility is that stored state is committed before relation data is updated successfully, so after `relation-set` fails and juju retries, then the delta between stored state and relation data becomes zero, and logic is not executed.

https://github.com/canonical/cos-proxy-operator/blob/9bb0f2f1fbd48e6b9fcc8c6e3956ace6f205bd1c/lib/charms/nrpe_exporter/v0/nrpe_exporter.py#L303-L3108

**Comment by przemeklal** [comment]
It is accurate, thank you. For completeness, the relation data provided by nrpe:monitors is complete and you can find units there, while they're missing in `nrpe_lookup.csv`.
