### ISSUE TITLE
Regression: downstream-prometheus-scrape-relation-joined fails

### ISSUE THREAD

**Issue by przemeklal** [canonical/cos-proxy-operator#92]
### Bug Description

It seems that https://github.com/canonical/cos-proxy-operator/pull/89 introduced a regression.

### To Reproduce

1. Deploy cos-proxy
2. Relate it to nrpe (:monitors)
3. Relate cos-proxy to scrape-interval-config (or probably directly to Prometheus)

### Environment

cos-proxy latest/edge (rev 47)

### Relevant log output

```shell
unit-cos-proxy-monitors-0: 06:00:28 ERROR unit.cos-proxy-monitors/0.juju-log downstream-prometheus-scrape:660: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-cos-proxy-monitors-0/charm/./src/charm.py", line 501, in <module>
    main(COSProxyCharm)
  File "/var/lib/juju/agents/unit-cos-proxy-monitors-0/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-cos-proxy-monitors-0/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-cos-proxy-monitors-0/charm/venv/ops/framework.py", line 340, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-cos-proxy-monitors-0/charm/venv/ops/framework.py", line 842, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-cos-proxy-monitors-0/charm/venv/ops/framework.py", line 931, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-cos-proxy-monitors-0/charm/./src/charm.py", line 429, in _downstream_prometheus_scrape_relation_joined
    self._on_nrpe_targets_changed(None)
  File "/var/lib/juju/agents/unit-cos-proxy-monitors-0/charm/./src/charm.py", line 450, in _on_nrpe_targets_changed
    nrpes = cast(List[Dict[str, Any]], event.current_targets)
AttributeError: 'NoneType' object has no attribute 'current_targets'
unit-cos-proxy-monitors-0: 06:00:28 ERROR juju.worker.uniter.operation hook "downstream-prometheus-scrape-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1
```

### Additional context

It was a fresh deployment of cos-proxy.

**Comment by sed-i** [comment]
Odd that it didn't show up in stests/itests.
Will submit a fix shortly.

**Comment by sed-i** [comment]
Odd that it didn't show up in stests/itests.
Will submit a fix shortly.
